### ISSUE TITLE
Undefined variable: domains

### ISSUE THREAD

**Issue by ziodave** [CrowdTruth/CrowdTruth#47]
Hello,

When I try to import some images from Rijksmuseum ImageGetter, I can't get it to work, and I see the following exception reported in the logs:

```Next exception 'ErrorException' with message 'Undefined variable: domains (View: /var/www/crowdtruth/app/views/media/pages/upload.blade.php)' in /var/www/crowdtruth/app/storage/views/ed2282c2081770be0ec23cd1acb3f643:66
Stack trace:
#0 /var/www/crowdtruth/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(41): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException))
#1 /var/www/crowdtruth/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/crowdt...', Array)
#2 /var/www/crowdtruth/vendor/laravel/framework/src/Illuminate/View/View.php(134): Illuminate\View\Engines\CompilerEngine->get('/var/www/crowdt...', Array)
#3 /var/www/crowdtruth/vendor/laravel/framework/src/Illuminate/View/View.php(102): Illuminate\View\View->getContents()
#4 /var/www/crowdtruth/vendor/laravel/framework/src/Illuminate/View/View.php(76): Illuminate\View\View->renderContents()
#5 /var/www/crowdtruth/vendor/laravel/framework/src/Illuminate/Http/Response.php(70): Illuminate\View\View->render()
#6 /var/www/crowdtruth/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /var/www/crowdtruth/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1427): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /var/www/crowdtruth/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1003): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#9 /var/www/crowdtruth/vendor/laravel/framework/src/Illuminate/Routing/Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /var/www/crowdtruth/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /var/www/crowdtruth/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /var/www/crowdtruth/vendor/laravel/framework/src/Illuminate/Http/FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 /var/www/crowdtruth/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#14 /var/www/crowdtruth/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#15 /var/www/crowdtruth/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/crowdtruth/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/crowdtruth/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#18 /var/www/crowdtruth/public/index.php(49): Illuminate\Foundation\Application->run()
#19 {main} [] []```

Am I doing something wrong? Do I need to configure the domains somewhere?

Thanks.

**Comment by Bouncer** [comment]
This is probably caused by the absence of domains. Try to upload a csv file first and create a domain there manually.

Please let us know if it worked.

**Comment by ziodave** [comment]
Thanks, I now get another error on the Web UI: "Undefined index: image".

This is the form:
![form](https://www.dropbox.com/s/af3d6twpb23tw6h/crowdtruth-a.png?dl=1)

This is the response:
![response](https://www.dropbox.com/s/5qbk96pfliwnw5j/crowdtruth-b.png?dl=1)

**Comment by Bouncer** [comment]
Try choosing text as type of file.

**Comment by ziodave** [comment]
Thanks, with text I was able to upload. I am uploading a CSV file, but later in the Media section I don't see anything.

Right now the CSV file has only one column with URLs to images. Is this the right format?

**Comment by Bouncer** [comment]
You need to pre-process the file first. Here, you can control how to read the file and how to process and store the fields. On the media page, click on Actions, then Pre-process media, or go to `/media/preprocess/text`

**Comment by ziodave** [comment]
Thanks, I feel I am making huge steps forward. Now I am configuring the properties from the CSV. Which properties should I configure?

Currently I only set the image URL in the CSV.

**Comment by Bouncer** [comment]
If you only have a url in the csv file, that is probably the only property you will need to add. This might give problems though if there are duplicate urls. My advise is to always add some unique identification number with each row in the original file. In that case you would have to upload the file again.

**Comment by ziodave** [comment]
Okey, calling the properties "url" and "id" is ok?

**Comment by Bouncer** [comment]
That should not give any problems. The framework indexes which properties you use. You can view them at `/media/listindex`, or re-index them at `/media/refreshindex`. You have to refresh this manually at the moment though.
